#!/bin/sh
# Written by Yapei Xie and CBIG under MIT license: https://github.com/ThomasYeoLab/CBIG/blob/master/LICENSE.md

cd ~/storage
rsync -a --exclude .git CBIG/* Standalone_Xie2025_LBC
# remove useless stable projects
rm -r Standalone_Xie2025_LBC/stable_projects/brain_parcellation/Kong2022_ArealMSHBM
rm -r Standalone_Xie2025_LBC/stable_projects/predict_phenotypes/Chen2024_MMM
rm -r Standalone_Xie2025_LBC/stable_projects/predict_phenotypes/ChenOoi2023_ICCW
rm -r Standalone_Xie2025_LBC/stable_projects/predict_phenotypes/ChenTam2022_TRBPC
rm -r Standalone_Xie2025_LBC/stable_projects/predict_phenotypes/He2022_MM
rm -r Standalone_Xie2025_LBC/stable_projects/predict_phenotypes/Ooi2022_MMP
rm -r Standalone_Xie2025_LBC/stable_projects/predict_phenotypes/Ooi2024_ME
rm -r Standalone_Xie2025_LBC/stable_projects/preprocessing/CBIG2022_DiffProc
rm -r Standalone_Xie2025_LBC/stable_projects/preprocessing/Li2019_GSR
rm -r Standalone_Xie2025_LBC/stable_projects/preprocessing/Orban2020_tod
# remove duplicated License generated by Github
rm Standalone_Xie2025_LBC/LICENSE
